#
# Build stage
#
FROM maven:3.6.3-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:8
ARG JAR_FILE=target/pagamentos-0.0.1-SNAPSHOT.jar
ENV SPRING_PROFILE=dev
MAINTAINER Gustavo Schmitz
COPY ${JAR_FILE} /var/pagamentos.jar
WORKDIR /var/pagamentos
EXPOSE 8082
ENTRYPOINT ["java","-Dspring.profiles.active=${SPRING_PROFILE}","-jar","/var/pagamentos.jar"]

